name: 'Fuzzing actions'

on:
  push:
    branches:
      - main
    
jobs:
  fuzzing:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker
      run: |
        docker build -t fuzzing-container -f ./Week2/ProjectX2-main/Dockerfile .
      working-directory: ${{ github.workspace }}

    - name: Run Docker Container
      run: |
        docker run fuzzing-container
      working-directory: ${{ github.workspace }}