name: 'Fuzzing actions'

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  fuzzing:
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout
          uses: actions/checkout@v3
    
        - name: Build Docker
          run: |
            docker build -t fuzzing-container -f ./ProjectX2-main/Dockerfile .
    
        - name: Run Docker Container
          run: |
            docker run fuzzing-container
